server:
  port: 8081

spring:
  application:
    name: nacos-server
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml # 假如不配置，则nacos远程配置文件的后缀为.properties
        prefix: nacosserver
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev